//! Port excitation, dense LU, and S-parameter extraction.

#![allow(dead_code)]
// PlanarMoM::run (Task 10) consumes these.

use crate::basis::RwgBasis;
use crate::fill::impedance_matrix;
use crate::greens::FreeSpaceGreen;
use faer::Mat;
use faer::linalg::solvers::{PartialPivLu, Solve};
use num_complex::Complex64;
use yee_core::{Error, FreqRange};
use yee_io::touchstone::{File as TouchstoneFile, Format, FreqUnit};

/// Build a 1 V delta-gap RHS across every edge tagged with `port_tag`.
/// `b[k] = V × length_k` for port edges, zero elsewhere.
///
/// The delta-gap source model treats a port edge as carrying a 1 V impulse
/// across its gap; the Galerkin testing of that impulse against the RWG
/// basis on the same edge yields `length_k` (with V = 1) — exactly the
/// classical RWG port loading. All non-port basis indices remain zero.
pub(crate) fn delta_gap_rhs(basis: &RwgBasis, port_tag: u32) -> Mat<Complex64> {
    let n = basis.n_basis();
    let mut b = Mat::<Complex64>::zeros(n, 1);
    for k in basis.port_basis_indices(port_tag) {
        b[(k, 0)] = Complex64::new(basis.edges[k].length, 0.0);
    }
    b
}

/// Solve at a single frequency and return S11 referenced to `z0_ref`.
///
/// Pipeline:
/// 1. Build the free-space Green's function at `freq_hz`.
/// 2. Assemble the MPIE impedance matrix `Z` over the RWG basis.
/// 3. Build the delta-gap RHS `b` for `port_tag`.
/// 4. Factorise `Z = L U` (partial pivoting) and solve `Z i = b`.
/// 5. Recover the port current as the basis-weighted sum
///    `I_port = Σ_k b_k · i_k` over port edges. This is the Galerkin
///    projection of the testing-weighted current back onto the port,
///    and matches the inner product that defines `b`.
/// 6. Return `S11 = (Z_in − Z0) / (Z_in + Z0)` with `Z_in = 1 V / I_port`.
///
/// Returns [`Error::Numerical`] if `|I_port|` drops below `1e-30`, which
/// indicates a pathological port tagging (no real current driven).
pub(crate) fn s_parameters_at_freq(
    basis: &RwgBasis,
    port_tag: u32,
    freq_hz: f64,
    z0_ref: f64,
) -> Result<Complex64, Error> {
    let green = FreeSpaceGreen::new(freq_hz);
    let z = impedance_matrix(basis, &green);
    let b = delta_gap_rhs(basis, port_tag);

    // Partial-pivot LU is the canonical dense solver for the (non-Hermitian
    // but symmetric) MPIE impedance matrix; full pivoting is overkill and
    // QR would needlessly inflate the constant factor on the O(N^3) work.
    let lu = PartialPivLu::new(z.as_ref());
    let i = lu.solve(b.as_ref());

    // Basis-weighted port current: Σ_k b_k · i_k over port edges. Because
    // `b_k = length_k` (real) on port edges, this is the standard RWG port
    // current. We do not sum over non-port edges because `b_k = 0` there.
    let mut i_port = Complex64::new(0.0, 0.0);
    for k in basis.port_basis_indices(port_tag) {
        i_port += b[(k, 0)] * i[(k, 0)];
    }

    if i_port.norm() < 1e-30 {
        return Err(Error::Numerical(
            "port current vanished; check port tagging".into(),
        ));
    }

    let v_port = Complex64::new(1.0, 0.0);
    let z_in = v_port / i_port;
    let z0 = Complex64::new(z0_ref, 0.0);
    Ok((z_in - z0) / (z_in + z0))
}

/// Run the sweep and produce a Touchstone file (Format::RealImag, FreqUnit::Hz).
///
/// One `s_parameters_at_freq` call per frequency in `freq_range`. The
/// resulting `TouchstoneFile` is filled with all fields populated — z0,
/// freq_unit, format, n_ports, freq_hz, data, and a single attribution
/// comment — so it round-trips through `yee_io::touchstone::write` without
/// further massaging.
pub(crate) fn s_parameters_sweep(
    basis: &RwgBasis,
    port_tag: u32,
    freq_range: FreqRange,
    z0_ref: f64,
) -> Result<TouchstoneFile, Error> {
    let mut freq_hz = Vec::new();
    let mut data: Vec<Vec<Complex64>> = Vec::new();
    for f in freq_range.iter() {
        let s11 = s_parameters_at_freq(basis, port_tag, f, z0_ref)?;
        freq_hz.push(f);
        data.push(vec![s11]);
    }
    Ok(TouchstoneFile {
        n_ports: 1,
        z0: z0_ref,
        freq_unit: FreqUnit::Hz,
        format: Format::RealImag,
        freq_hz,
        data,
        comments: vec!["! Generated by yee-mom Phase 1.0 free-space dipole solver".to_string()],
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::basis::RwgBasis;
    use nalgebra::Vector3;
    use yee_mesh::TriMesh;

    fn two_tri_mesh_with_port() -> TriMesh {
        let vertices = vec![
            Vector3::new(0.0, 0.0, 0.0),
            Vector3::new(0.1, 0.0, 0.0),
            Vector3::new(0.1, 0.1, 0.0),
            Vector3::new(0.0, 0.1, 0.0),
        ];
        let triangles = vec![[0u32, 1, 2], [0u32, 2, 3]];
        // Different non-zero tags → shared diagonal edge is the port edge
        // under the "boundary between two tagged regions" port rule.
        // `port_basis_indices(1)` matches because `min(1, 2) == 1`.
        let tags = vec![1u32, 2u32];
        TriMesh::new(vertices, triangles, tags).unwrap()
    }

    #[test]
    fn delta_gap_rhs_length_weighting() {
        let basis = RwgBasis::from_mesh(two_tri_mesh_with_port()).unwrap();
        let b = delta_gap_rhs(&basis, 1);
        let port_indices: Vec<usize> = basis.port_basis_indices(1).collect();
        assert!(!port_indices.is_empty(), "expected at least one port edge");
        for k in port_indices {
            let expected = basis.edges[k].length;
            assert!((b[(k, 0)].re - expected).abs() < 1e-12);
            assert!(b[(k, 0)].im.abs() < 1e-12);
        }
    }

    #[test]
    fn sweep_produces_n_points_rows() {
        let basis = RwgBasis::from_mesh(two_tri_mesh_with_port()).unwrap();
        let freq = FreqRange::new(1.0e9, 1.5e9, 3).unwrap();
        let file = s_parameters_sweep(&basis, 1, freq, 50.0).expect("sweep");
        assert_eq!(file.freq_hz.len(), 3);
        assert_eq!(file.data.len(), 3);
        assert_eq!(file.n_ports, 1);
        assert!(matches!(file.format, Format::RealImag));
        assert!(matches!(file.freq_unit, FreqUnit::Hz));
    }
}
