"""Yee electromagnetic simulation — Python bindings."""

from yee._yee import (
    AlConfig,
    AlResult,
    BoConfig,
    BoResult,
    CavityQResult,
    CavityResonanceResult,
    DipolePatternResult,
    FdtdDriver,
    FdtdDriverConfig,
    FdtdRadiationPattern,
    FreqRange,
    FresnelTfsfResult,
    GaussianProcess,
    Nsga2Config,
    Nsga2Result,
    PlanarMoM,
    SParameters,
    TriMesh,
    ValidationCase,
    ValidationReport,
    __version__,
    active_learn,
    eigensolver,
    fem,
    nsga2_minimize,
    run_cavity_q,
    run_cavity_resonance,
    run_dipole_pattern,
    run_fresnel_tfsf,
    run_validation,
    s11_db,
    s11_phase,
    smith_xy,
    touchstone,
)
from yee._yee import minimize as bo_minimize

# `yee.design` is a hybrid module: the Rust-side `_yee.design` submodule
# carries the schema accessor and the `SchemaRejectedError` class, but the
# `from_prompt_llm` sidecar lives in pure Python at `yee/design.py` to keep
# the Anthropic SDK out of the Rust build path (spec §11). Import it last so
# the Rust submodule is fully registered in `sys.modules` first.
from yee import design  # noqa: E402

__all__ = [
    "AlConfig",
    "AlResult",
    "BoConfig",
    "BoResult",
    "CavityQResult",
    "CavityResonanceResult",
    "DipolePatternResult",
    "FdtdDriver",
    "FdtdDriverConfig",
    "FdtdRadiationPattern",
    "FreqRange",
    "FresnelTfsfResult",
    "GaussianProcess",
    "Nsga2Config",
    "Nsga2Result",
    "PlanarMoM",
    "SParameters",
    "TriMesh",
    "ValidationCase",
    "ValidationReport",
    "__version__",
    "active_learn",
    "bo_minimize",
    "design",
    "eigensolver",
    "fem",
    "nsga2_minimize",
    "run_cavity_q",
    "run_cavity_resonance",
    "run_dipole_pattern",
    "run_fresnel_tfsf",
    "run_validation",
    "s11_db",
    "s11_phase",
    "smith_xy",
    "touchstone",
]
