//! # yee-mesh
//!
//! Meshing for Yee. The `gmsh` feature enables in-tree bindgen-generated FFI against
//! the upstream `gmshc.h` (Gmsh 4.15+). Without the feature this crate exposes only
//! the safe data structures (triangle mesh, hex grid) so downstream crates compile
//! on hosts without a Gmsh SDK.
//!
//! The pre-existing `rgmsh` crate is unmaintained since 2019 and targets Gmsh 4.4.1;
//! we generate fresh bindings (see `build.rs` in Phase 0).

// Phase 0 forbade `unsafe_code` crate-wide. Phase 1.mesh.0 must call into
// the Gmsh C API via `bindgen`, which is inherently `unsafe`. We narrow the
// forbid to the no-feature build (where the crate is pure data structures)
// and rely on localized `#[allow(unsafe_code)]` inside the FFI submodule.
#![cfg_attr(not(feature = "gmsh"), forbid(unsafe_code))]
#![warn(missing_docs)]

use nalgebra::Vector3;

mod cavity;
pub mod kicad;
mod session;
mod tetmesh;

pub use kicad::{KiCadBoard, KiCadError, LayerInfo, Segment, Zone};
pub use session::Session;
pub use tetmesh::TetMesh3D;

/// Meshing errors.
#[derive(Debug, thiserror::Error)]
pub enum Error {
    /// Built without the `gmsh` feature.
    #[error("yee-mesh built without the `gmsh` feature; rebuild with --features gmsh")]
    NotEnabled,
    /// Gmsh returned a non-zero status from its C API.
    #[error("gmsh error code {0}")]
    Gmsh(i32),
    /// Geometry validation failed before meshing.
    #[error("invalid geometry: {0}")]
    Invalid(String),
}

/// Mesh-layer result alias.
pub type Result<T> = core::result::Result<T, Error>;

/// A planar triangle mesh — the primary input to `yee-mom`.
#[derive(Debug, Default, Clone)]
pub struct TriMesh {
    /// Vertices in world coordinates.
    pub vertices: Vec<Vector3<f64>>,
    /// Triangle indices into `vertices`, 3 per face.
    pub triangles: Vec<[u32; 3]>,
    /// Per-triangle physical-group tag (used to map ports, materials).
    pub tags: Vec<u32>,
}

impl TriMesh {
    /// Build a `TriMesh` after validating its invariants.
    ///
    /// Currently the only invariant enforced is that there is exactly one
    /// tag per triangle. Returns [`Error::Invalid`] with a descriptive
    /// message when `triangles.len() != tags.len()`.
    ///
    /// Phase 1 will additionally validate that each triangle index is
    /// `< vertices.len()`.
    pub fn new(
        vertices: Vec<Vector3<f64>>,
        triangles: Vec<[u32; 3]>,
        tags: Vec<u32>,
    ) -> Result<Self> {
        if triangles.len() != tags.len() {
            return Err(Error::Invalid(format!(
                "triangles ({}) and tags ({}) must have equal length",
                triangles.len(),
                tags.len()
            )));
        }
        Ok(Self {
            vertices,
            triangles,
            tags,
        })
    }

    /// Number of triangles.
    pub fn n_tris(&self) -> usize {
        self.triangles.len()
    }
}

/// Material identifier carried by 2-D cross-section meshes.
///
/// `u32` matches the existing tag convention used by [`TriMesh::tags`] for
/// the 3-D surface mesh and by `yee-mom`'s port-tag handling. Keeping the
/// same width and signedness keeps mesh- and port-tag plumbing uniform.
pub type MaterialTag = u32;

/// A planar 2-D triangle mesh — the input contract for the Phase 1.3.1.1
/// wave-port cross-section eigensolver in `yee-mom`.
///
/// Unlike [`TriMesh`] (3-D surface mesh used by the planar MoM solver), a
/// `TriMesh2D` lives in the port cross-section plane and is generated by
/// the caller (Gmsh, hand-rolled fixtures, or any other mesher). Each
/// vertex carries a [`MaterialTag`] so a vertex sitting on a dielectric
/// interface can be distinguished from one in bulk; each triangle carries
/// a [`MaterialTag`] selecting the region's material (typed in `yee-mom`
/// as an `eps_r` / `mu_r` lookup keyed by tag).
///
/// **Status:** Phase 1.3.1.1 step 0-1 stub. The Nedelec edge-element
/// eigensolve that consumes this mesh lands in step 2-5; the type is
/// shipped first so the public API surface and material-keying contract
/// freeze before the assembly code is written.
#[derive(Debug, Default, Clone)]
pub struct TriMesh2D {
    /// Vertices in cross-section coordinates `(x, y)`, metres.
    pub vertices: Vec<[f64; 2]>,
    /// Triangle vertex indices, 3 per triangle, counter-clockwise winding
    /// expected (positive shoelace area). Indices reference [`Self::vertices`].
    pub triangles: Vec<[usize; 3]>,
    /// Per-vertex material tag. Length matches [`Self::vertices`]. Used by
    /// the eigensolver to enforce material-interface continuity conditions
    /// on the longitudinal (`E_z`) nodal DoFs.
    pub vertex_material: Vec<MaterialTag>,
    /// Per-triangle material tag. Length matches [`Self::triangles`]. The
    /// eigensolver looks up `eps_r` / `mu_r` from this tag during element-
    /// matrix assembly.
    pub triangle_material: Vec<MaterialTag>,
}

impl TriMesh2D {
    /// Build a `TriMesh2D` after validating its invariants.
    ///
    /// Enforced invariants:
    /// * `vertices.len() >= 3` (need at least one triangle's worth of vertices).
    /// * `triangles.len() >= 1`.
    /// * Every triangle index is `< vertices.len()` — out-of-range indices
    ///   are rejected at construction time so downstream consumers can
    ///   index without bounds checks.
    /// * Every triangle has strictly positive signed area (shoelace).
    ///   Counter-clockwise winding is the convention; clockwise or
    ///   degenerate (collinear vertex) triangles are rejected.
    ///
    /// Material tags default to `0` for every vertex and every triangle if
    /// the caller did not supply them — pass `vertex_material = None` to
    /// fill with zeros, or `Some(vec)` to supply explicit tags. The
    /// `Some` arm enforces `vec.len() == vertices.len()`. Same shape for
    /// `triangle_material`.
    ///
    /// Returns [`Error::Invalid`] with a descriptive message on any
    /// invariant violation.
    pub fn new(
        vertices: Vec<[f64; 2]>,
        triangles: Vec<[usize; 3]>,
        vertex_material: Option<Vec<MaterialTag>>,
        triangle_material: Option<Vec<MaterialTag>>,
    ) -> Result<Self> {
        if vertices.len() < 3 {
            return Err(Error::Invalid(format!(
                "TriMesh2D requires >= 3 vertices, got {}",
                vertices.len()
            )));
        }
        if triangles.is_empty() {
            return Err(Error::Invalid(
                "TriMesh2D requires >= 1 triangle".to_string(),
            ));
        }
        for (i, tri) in triangles.iter().enumerate() {
            for &idx in tri {
                if idx >= vertices.len() {
                    return Err(Error::Invalid(format!(
                        "triangle {i} references vertex index {idx} >= vertex count {}",
                        vertices.len()
                    )));
                }
            }
            // Signed area via shoelace; must be strictly positive to
            // reject collinear / clockwise triangles.
            let v0 = vertices[tri[0]];
            let v1 = vertices[tri[1]];
            let v2 = vertices[tri[2]];
            let area =
                0.5 * ((v1[0] - v0[0]) * (v2[1] - v0[1]) - (v2[0] - v0[0]) * (v1[1] - v0[1]));
            if !area.is_finite() || area <= 0.0 {
                return Err(Error::Invalid(format!(
                    "triangle {i} has non-positive signed area {area} (degenerate or CW winding)"
                )));
            }
        }
        let vertex_material = match vertex_material {
            Some(v) => {
                if v.len() != vertices.len() {
                    return Err(Error::Invalid(format!(
                        "vertex_material ({}) must match vertices ({})",
                        v.len(),
                        vertices.len()
                    )));
                }
                v
            }
            None => vec![0; vertices.len()],
        };
        let triangle_material = match triangle_material {
            Some(v) => {
                if v.len() != triangles.len() {
                    return Err(Error::Invalid(format!(
                        "triangle_material ({}) must match triangles ({})",
                        v.len(),
                        triangles.len()
                    )));
                }
                v
            }
            None => vec![0; triangles.len()],
        };
        Ok(Self {
            vertices,
            triangles,
            vertex_material,
            triangle_material,
        })
    }

    /// Number of triangles.
    pub fn n_tris(&self) -> usize {
        self.triangles.len()
    }

    /// Number of vertices.
    pub fn n_verts(&self) -> usize {
        self.vertices.len()
    }

    /// Signed area of triangle `i` via the shoelace formula. Positive for
    /// CCW winding (the convention enforced by [`Self::new`]).
    ///
    /// # Panics
    /// Panics if `i >= self.n_tris()`. Callers driven by the eigensolver
    /// iterate over `0..n_tris()` so the bounds check is upheld by
    /// construction.
    pub fn area(&self, i: usize) -> f64 {
        let tri = self.triangles[i];
        let v0 = self.vertices[tri[0]];
        let v1 = self.vertices[tri[1]];
        let v2 = self.vertices[tri[2]];
        0.5 * ((v1[0] - v0[0]) * (v2[1] - v0[1]) - (v2[0] - v0[0]) * (v1[1] - v0[1]))
    }

    /// Centroid of triangle `i` — arithmetic mean of its three vertices.
    ///
    /// # Panics
    /// Panics if `i >= self.n_tris()`. Same rationale as [`Self::area`].
    pub fn centroid(&self, i: usize) -> [f64; 2] {
        let tri = self.triangles[i];
        let v0 = self.vertices[tri[0]];
        let v1 = self.vertices[tri[1]];
        let v2 = self.vertices[tri[2]];
        [(v0[0] + v1[0] + v2[0]) / 3.0, (v0[1] + v1[1] + v2[1]) / 3.0]
    }
}

#[cfg(test)]
mod tri_mesh_2d_tests {
    use super::*;

    fn unit_square_mesh() -> TriMesh2D {
        // Two CCW triangles spanning the unit square [0,1]^2.
        let vertices = vec![[0.0, 0.0], [1.0, 0.0], [1.0, 1.0], [0.0, 1.0]];
        let triangles = vec![[0, 1, 2], [0, 2, 3]];
        TriMesh2D::new(vertices, triangles, None, None).unwrap()
    }

    #[test]
    fn construct_valid_unit_square_two_tris() {
        let m = unit_square_mesh();
        assert_eq!(m.n_verts(), 4);
        assert_eq!(m.n_tris(), 2);
        // Default material tags are 0.
        assert_eq!(m.vertex_material, vec![0u32; 4]);
        assert_eq!(m.triangle_material, vec![0u32; 2]);
    }

    #[test]
    fn out_of_range_triangle_index_rejected() {
        let vertices = vec![[0.0, 0.0], [1.0, 0.0], [0.0, 1.0]];
        // Index 9 is well past the 3 vertices.
        let triangles = vec![[0, 1, 9]];
        let err = TriMesh2D::new(vertices, triangles, None, None).unwrap_err();
        match err {
            Error::Invalid(msg) => {
                assert!(msg.contains("vertex index 9"), "got: {msg}");
            }
            _ => panic!("expected Invalid"),
        }
    }

    #[test]
    fn degenerate_collinear_triangle_rejected() {
        // Three collinear points → zero area → rejected.
        let vertices = vec![[0.0, 0.0], [1.0, 0.0], [2.0, 0.0]];
        let triangles = vec![[0, 1, 2]];
        let err = TriMesh2D::new(vertices, triangles, None, None).unwrap_err();
        match err {
            Error::Invalid(msg) => {
                assert!(msg.contains("non-positive signed area"), "got: {msg}");
            }
            _ => panic!("expected Invalid"),
        }
    }

    #[test]
    fn clockwise_winding_rejected() {
        // CW winding → negative area → rejected (the eigensolver assumes CCW).
        let vertices = vec![[0.0, 0.0], [0.0, 1.0], [1.0, 0.0]];
        let triangles = vec![[0, 1, 2]];
        let err = TriMesh2D::new(vertices, triangles, None, None).unwrap_err();
        match err {
            Error::Invalid(msg) => {
                assert!(msg.contains("non-positive signed area"), "got: {msg}");
            }
            _ => panic!("expected Invalid"),
        }
    }

    #[test]
    fn area_matches_shoelace_hand_calc() {
        // Right triangle with legs 1.0 and 2.0 → area 1.0.
        let vertices = vec![[0.0, 0.0], [1.0, 0.0], [0.0, 2.0]];
        let triangles = vec![[0, 1, 2]];
        let m = TriMesh2D::new(vertices, triangles, None, None).unwrap();
        assert!((m.area(0) - 1.0).abs() < 1e-15);
    }

    #[test]
    fn centroid_matches_hand_calc() {
        // Centroid of (0,0), (3,0), (0,3) is (1, 1).
        let vertices = vec![[0.0, 0.0], [3.0, 0.0], [0.0, 3.0]];
        let triangles = vec![[0, 1, 2]];
        let m = TriMesh2D::new(vertices, triangles, None, None).unwrap();
        let c = m.centroid(0);
        assert!((c[0] - 1.0).abs() < 1e-15);
        assert!((c[1] - 1.0).abs() < 1e-15);
    }

    #[test]
    fn material_length_mismatch_rejected() {
        let vertices = vec![[0.0, 0.0], [1.0, 0.0], [0.0, 1.0]];
        let triangles = vec![[0, 1, 2]];
        let err = TriMesh2D::new(
            vertices,
            triangles,
            Some(vec![1, 2]), // length 2, but 3 vertices
            None,
        )
        .unwrap_err();
        match err {
            Error::Invalid(msg) => assert!(msg.contains("vertex_material"), "got: {msg}"),
            _ => panic!("expected Invalid"),
        }
    }

    #[test]
    fn explicit_material_tags_preserved() {
        let vertices = vec![[0.0, 0.0], [1.0, 0.0], [0.0, 1.0], [1.0, 1.0]];
        let triangles = vec![[0, 1, 2], [1, 3, 2]];
        let m = TriMesh2D::new(
            vertices,
            triangles,
            Some(vec![1, 2, 3, 4]),
            Some(vec![10, 20]),
        )
        .unwrap();
        assert_eq!(m.vertex_material, vec![1, 2, 3, 4]);
        assert_eq!(m.triangle_material, vec![10, 20]);
    }
}
